# Generated by Django 4.2.6 on 2024-05-06 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000, null=True)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='')),
                ('imagen2', models.ImageField(upload_to='')),
                ('imagen3', models.ImageField(upload_to='')),
                ('categorias', models.ManyToManyField(to='tfg_app.categoria')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg_app.perfil')),
            ],
        ),
    ]
