# Generated by Django 4.2.6 on 2024-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0005_producto_create_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografía',
            field=models.TextField(blank=True, null=True),
        ),
    ]
