# Generated by Django 4.2.6 on 2024-05-14 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0006_perfil_biografía'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
