# Generated by Django 5.0.6 on 2024-05-14 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0007_perfil_create_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tfg_app.perfil'),
        ),
    ]
