# Generated by Django 5.0.6 on 2024-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='media/perfil/blankprofile.webp', upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
    ]
