# Generated by Django 5.0.6 on 2024-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0010_alter_perfil_foto_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='edad',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfil/blankprofile.webp', upload_to='perfil'),
        ),
    ]
