# Generated by Django 5.0.6 on 2024-05-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0011_remove_perfil_edad_perfil_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tfg_app.categoria'),
            preserve_default=False,
        ),
    ]
